First Validations (BaseTx + Payment)
Peersyst/xrpl-go pull request #16
Opened 2024-09-03 12:33 UTC by florent-uzio

This PR adds validation for the base tx fields and for the payment transaction.

It also adds a few helpers such as `IsString`, `IsInt` etc.

2024-09-04 10:22 UTC, GuillemGarciaDev requested changes

2024-09-04 10:22 UTC, GuillemGarciaDev commented on xrpl/model/transactions/payment.go
> +		panic("Missing field Amount")
We cannot force a panic in the package. We should expose the error to the user, delegating the handling of the error

2024-09-04 10:22 UTC, GuillemGarciaDev commented on xrpl/model/transactions/payment.go
> +		panic("Invalid field Amount")
Idem

2024-09-04 10:22 UTC, GuillemGarciaDev commented on xrpl/model/transactions/payment.go
> +			panic("Invalid field Paths")
Idem

2024-09-04 10:22 UTC, GuillemGarciaDev commented on xrpl/model/transactions/payment.go
> +			panic("Payment transaction: tfPartialPayment flag required with DeliverMin")
Idem

2024-09-04 10:22 UTC, GuillemGarciaDev commented on xrpl/model/transactions/validations_commons.go
> +		panic(field + " is missing")
Return errors instead of panic

2024-09-04 10:22 UTC, GuillemGarciaDev commented on xrpl/utils/typecheck/typecheck.go
Its okey to have this helper functions, I would move them into `pkg` folder to use it globally since it is not heavily related to transactions or models

2024-09-04 10:22 UTC, GuillemGarciaDev commented on xrpl/utils/map_utils/map_utils.go
Also move it to `pkg`

2024-09-04 13:57 UTC, florent-uzio commented
Hi @GuillemGarciaDev , I updated the code from your comments. It's ready for another review.

2024-09-06 14:03 UTC, GuillemGarciaDev approved these changes

2024-09-06 14:04 UTC, merged