AMMBid transaction
Peersyst/xrpl-go pull request #35
Opened 2024-10-15 13:27 UTC by florent-uzio

# Title

This PR aims to add the struct, `Flatten` func and `Validate` func for the `AMMBid` transaction type.
It also adds the relevant tests.

## Changes

- `AMMBid` transaction type
- `IsAsset` func
- Relevant tests
- Flatten functions for some of the AMM struct + tests

2024-10-16 14:24 UTC, GuillemGarciaDev requested changes

2024-10-16 14:24 UTC, GuillemGarciaDev commented on xrpl/transaction/amm_bid.go
> +	// TODO: check that the AuthAccount 'Account' field is a valid XRP address when this function is available
I think there's already a function to check this

2024-10-16 14:24 UTC, GuillemGarciaDev commented on xrpl/transaction/amm_bid_test.go
There're some errors that are not covered by tests. It would be nice to cover them on each test 👍🏻

2024-10-16 14:24 UTC, GuillemGarciaDev commented on xrpl/ledger-entry-types/amm_test.go
Test coverage should be improved (currently a 69%)

2024-10-16 14:24 UTC, GuillemGarciaDev commented on xrpl/transaction/validations_xrpl_objects_test.go
Nice! Lets improve the test coverage and its done

2024-10-17 11:37 UTC, florent-uzio commented on xrpl/transaction/amm_bid_test.go
We have now 100% coverage

2024-10-17 11:37 UTC, florent-uzio commented on xrpl/ledger-entry-types/amm_test.go
We have now 100% coverage

2024-10-17 11:37 UTC, florent-uzio commented on xrpl/transaction/validations_xrpl_objects_test.go
We have now 100% coverage for this as well

2024-10-17 11:39 UTC, florent-uzio commented
![image](https://github.com/user-attachments/assets/689130cf-733f-41b7-a975-c6538fa7c14e)

![image](https://github.com/user-attachments/assets/5e0f546d-c81d-466b-ba43-fbc2d7d8a5e3)

![image](https://github.com/user-attachments/assets/5a19defa-4a6f-4eaa-b481-bb4eff8a0edf)

@GuillemGarciaDev all three mentioned in the comments have now 100% test coverage.

2024-10-17 14:14 UTC, GuillemGarciaDev approved these changes

2024-10-17 14:14 UTC, merged