AMMWithdraw
Peersyst/xrpl-go pull request #43
Opened 2024-10-21 12:00 UTC by florent-uzio

# Title

This PR aims to add the `AMMWithdraw` type with:
- Validate() + tests
- Flatten() + tests
- Add a `IsZero` function to IssuedCurrency objects to check if the object is empty or not. The PR adds tests for this func also.

It also refactors some flags which are share between `AMMWithdraw` and `AMMDeposit`. Those shared flags are placed in a `amm_common.go` file.

AMMWithdraw has 100% coverage tests.

![image](https://github.com/user-attachments/assets/d946886e-18de-4951-9d48-c7e48f17519e)

## Changes

- Change 1
- Change 2

## Notes (optional)

Describe any additional notes here.

2024-10-21 14:07 UTC, GuillemGarciaDev requested changes

2024-10-21 14:07 UTC, GuillemGarciaDev commented on xrpl/transaction/amm_common.go
> +	tfLPToken         uint = 65536
Add flag comments

2024-10-21 14:07 UTC, GuillemGarciaDev commented on xrpl/transaction/amm_withdraw.go
> +func (a *AMMWithdraw) Flatten() FlatTransaction {
Add comment

2024-10-21 14:07 UTC, GuillemGarciaDev commented on xrpl/transaction/amm_withdraw.go
>  func (*AMMWithdraw) TxType() TxType {
Add comment

2024-10-21 14:07 UTC, GuillemGarciaDev commented on xrpl/transaction/amm_withdraw.go
> +func (a *AMMWithdraw) Validate() (bool, error) {
Add comment

2024-10-22 06:54 UTC, florent-uzio commented on xrpl/transaction/amm_common.go
> +	tfLPToken         uint = 65536
Done.

2024-10-23 08:34 UTC, GuillemGarciaDev approved these changes

2024-10-23 08:35 UTC, merged