TicketCreate
Peersyst/xrpl-go pull request #46
Opened 2024-10-23 11:53 UTC by florent-uzio

# Title

This PR aims to:

- Complete the TicketCreate missing functions
- Add the relevant tests

![image](https://github.com/user-attachments/assets/9783dd48-b129-4c45-8e7a-e7774e8114cf)

2024-10-23 11:56 UTC, florent-uzio commented on coverage.html
> +// Create a new Automated Market Maker (AMM) instance for trading a pair of assets (fungible tokens or XRP).
I forgot to re-run `make coverage-unit` in my previous PR where I added some comments for AMMCreate and AMMDelete.

2024-10-28 08:31 UTC, GuillemGarciaDev requested changes

2024-10-28 08:31 UTC, GuillemGarciaDev commented on xrpl/transaction/ticket_create.go
> +	if t.TicketCount == 0 || t.TicketCount > 250 {
we can store the minimum and maximum values in constants for better readability

2024-10-28 08:31 UTC, GuillemGarciaDev commented on xrpl/transaction/ticket_create.go
> +		return false, errors.New("ticketCount must be greater than 0 and less than or equal to 250")
Update error formatting with `TicketCount` range constants

2024-10-31 17:32 UTC, GuillemGarciaDev approved these changes

2024-10-31 17:34 UTC, merged