Feat/xrpl/basetx validate updates
Peersyst/xrpl-go pull request #47
Opened 2024-10-25 10:35 UTC by florent-uzio

# Title

This PR aims to remove some unused func from `tx.go`: `UnmarshallTx` and remove the use of that func in some tests files.
Tx.go has 100% test coverage.
I will update in a later PR the coverage for `AMMBid` which seems to have decreased.

![image](https://github.com/user-attachments/assets/fcb02f99-d9af-4d7a-9680-86314ea3d482)

## Changes

- Change 1
- Change 2

## Notes (optional)

Describe any additional notes here.

2024-10-28 08:57 UTC, GuillemGarciaDev requested changes
I would also remove the `UnmarshalTx` method on every transaction. Good PR!

2024-10-31 09:26 UTC, florent-uzio commented
@GuillemGarciaDev I removed the other `UnmarshallJSON` function from the remaning transaction types and the test files. It's ready for another review

2024-11-04 08:10 UTC, GuillemGarciaDev requested changes

2024-11-04 08:10 UTC, GuillemGarciaDev commented on xrpl/transaction/tx.go
Why  are the BaseTx field validations on `Validate` method being deleted? 🤔

2024-11-04 13:32 UTC, florent-uzio commented on xrpl/transaction/tx.go
I originally looked at `xrpl.js` for the validation. And I forgot the fact that `xrpl.js` can be used with Javascript (not only typescript) which allows to define whatever type of field. So it is important there to check that Sequence is a number, Fee is a string etc.
But Go has types and it is not possible to define whatever we want for a field. This is why I removed the validations.
Does that make sense?

2024-11-04 15:55 UTC, GuillemGarciaDev commented on xrpl/transaction/tx.go
Yes, but field value validation should be also done. We should validate that fields like `Fee` have a correct numeric value despite their are of type string, and so on. Can you restore the changes and add these validations? 🙏🏻

2024-11-08 14:46 UTC, GuillemGarciaDev approved these changes

2024-11-08 14:58 UTC, merged