SignerListSet and SetRegularKey
Peersyst/xrpl-go pull request #50
Opened 2024-11-04 12:43 UTC by florent-uzio

# Title

This PR aims to add the `Validate` and `Flatten` function to `SetRegularKey` and `SignerListSet`.
The tests have 100% coverage.
The PR also adds comments for the SignerList entry and the relevant `Flatten` functions.

2024-11-07 09:53 UTC, florent-uzio commented
@GuillemGarciaDev , gentle reminder about this PR as well

2024-11-08 09:12 UTC, GuillemGarciaDev requested changes

2024-11-08 09:12 UTC, GuillemGarciaDev commented on xrpl/ledger-entry-types/signer_list.go
> +	SignerListID uint64
It is an `uint32`

2024-11-08 09:12 UTC, GuillemGarciaDev commented on xrpl/ledger-entry-types/signer_list.go
> +	SignerQuorum uint64
`uint32`

2024-11-08 09:12 UTC, GuillemGarciaDev commented on xrpl/ledger-entry-types/signer_list.go
>  	PreviousTxnLgrSeq uint64
`uint32`

2024-11-08 09:12 UTC, GuillemGarciaDev commented on xrpl/ledger-entry-types/signer_list.go
we should add the `Flatten` method for `SignerList`

2024-11-08 09:12 UTC, GuillemGarciaDev commented on xrpl/ledger-entry-types/signer_list.go
> +	if s.SignerEntry != (SignerEntry{}) {
This condition is no neeeded

2024-11-08 09:12 UTC, GuillemGarciaDev commented on xrpl/transaction/signer_list_set.go
> +	if len(s.SignerEntries) < MIN_SIGNERS || len(s.SignerEntries) > MAX_SIGNERS {
rename all uppercase constants to camelcase

2024-11-08 15:49 UTC, GuillemGarciaDev approved these changes

2024-11-08 15:59 UTC, merged